name: 3D GitHub Contribution Updater

on:
  schedule:
    - cron: "30 12 * * *"  # 12:30 PM UTC daily (adjust to your timezone)
  workflow_dispatch:       # Allows manual runs
  push:
    branches: [ main ]     # Optional: Run when README changes
    paths: [ 'README.md' ]

jobs:
  generate-contributions:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # Required for pushing changes
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Gets full git history

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@v0.9.2  # Pinned version
        with:
          username: ${{ github.repository_owner }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || secrets.PERSONAL_ACCESS_TOKEN }}
          THEME: "night-rainbow"  # Best looking theme
          INCLUDE_PRIVATE: "true"  # Include private contributions
          YEAR: "last-3-years"    # Options: current-year, last-year, last-3-years, or specific years "2022,2023,2024"
          MAX_REPOS: 100           # Increase if you have many repos
          ENABLE_ANIMATION: "true" # Smoother visuals

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./profile-3d-contrib/
          git commit -m "🔄 Auto-update 3D contribution graph [skip ci]" || echo "No changes to commit"
          git push
