name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "30 12 * * *"  # 12:30 PM UTC daily
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'README.md' ]

jobs:
  generate-contributions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@latest
        with:
          username: ${{ github.repository_owner }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || secrets.PERSONAL_ACCESS_TOKEN }}
          THEME: "night-rainbow"
          INCLUDE_PRIVATE: "true"
          YEAR: "last-3-years"
          MAX_REPOS: 100
          ENABLE_ANIMATION: "true"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./profile-3d-contrib/
          git commit -m "🔄 Auto-update 3D contribution graph [skip ci]" || echo "No changes to commit"
          git push
